### ISSUE TITLE
Moving to bzlmod ? 

### ISSUE THREAD

**Issue by oh-tarnished** [mvukov/rules_ros2#161]
Hey @mvukov , Any plans to move to `bzlmod` ?

**Comment by oh-tarnished** [comment]
ignore this will raise it from my personal acco

**Comment by mvukov** [comment]
Hello, I don't have plans to support bzlmod short-term. IMO, it's a good future-proof initiative.

**Comment by oh-tarnished** [comment]
I was thinking of making a PR. would it be okay ? I think by end of this lifecycle of bazel 6.

**Comment by mvukov** [comment]
:+1: Sounds good.

**Comment by oh-tarnished** [comment]
Hey Again, 

Did you consider moving all the python deps to `poetry project` ? instead of pip ? I love how poetry handles the dependencies and cross-compile your code. 

Someone already made a bazel rules for that were are using it. [rules_poetry](https://github.com/oxidase/rules_poetry)

suggestion to move all the python deps to poetry ..

**Comment by mvukov** [comment]
I am thinking to use poetry as a dep resolver instead of pip-compile. pip-compile cannot resolve deps for another platform, but poetry can -- thinking here about arm64. I have never used rules_poetry. Didn't look into the details, but, not declaring each dep as a separate workspace (but having all deps in a single workspace) doesn't allow for incremental downloads. This could be a serious issue once you have a lot of deps. I've used rules_python when it didn't have incremental downloads and it wasn't so convenient.

How does poetry solve cross-compilation issues? Does it use Bazel-provided cc toolchain(s)?

**Comment by oh-tarnished** [comment]
Well `rules_poetry` depends on `poetry.lock` file which has all the supported wheel files to compile. if for instance the wheel file doesn't exist for a particular architecture then it throws an error out. saying unsupported architecture based. how `pip` vendors each library for single architecture .... poetry does it for multiple and it doesn't use any cc-toolchains.

**Comment by mvukov** [comment]
IMO, it's sufficient to track https://github.com/mvukov/rules_ros2/pull/173.
